### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by Yuripetusko**

### CODE REVIEW

**Comment by rssnyder** [comment]
@Yuripetusko this change was already made last week, I just forgot to push my changes. Please see the updated version in master.

**Comment by Yuripetusko** [comment]
Thanks @rssnyder . 

I am not a python dev, but looking at this piece

```
t_reactions = await reaction.users(limit=50).flatten()
reactors.extend(t_reactions)
while len(t_reactions) == 50:
    t_reactions = await reaction.users(
        limit=50, after=t_reactions[0]
    ).flatten()
    reactors.extend(t_reactions)
```

Wouldn't it keep fetching the same 50 first people over and over? shouldn't it be `after=t_reactions[50]` instead of `after=t_reactions[0]` ?

**Comment by rssnyder** [comment]
> Thanks @rssnyder .
> 
> I am not a python dev, but looking at this piece
> 
> ```
> t_reactions = await reaction.users(limit=50).flatten()
> reactors.extend(t_reactions)
> while len(t_reactions) == 50:
>     t_reactions = await reaction.users(
>         limit=50, after=t_reactions[0]
>     ).flatten()
>     reactors.extend(t_reactions)
> ```
> 
> Wouldn't it keep fetching the same 50 first people over and over? shouldn't it be `after=t_reactions[50]` instead of `after=t_reactions[0]` ?

I thought the exact same thing, and coded it like that when I first was modifying that portion, but it lead to an infinite loop with a list of the same 50 users over and over. Switching it to this way resulted in the correct end result of all unique reactors.

**Comment by Yuripetusko** [comment]
Interesting, then perhaps it is sorted by newest first. The reason why I am enquiring is that we started seeing people winning twice in the same draw with over 1500 reactions, which is strange 🤔

**Pull request closed without merging**
